all:
	g++ -g main.cpp kd_tree.cpp -o main.x
	
mp: 
	g++ -fopenmp -g main.cpp kd_tree.cpp -o main.x

clean:
	rm *.x
	
	
#g++ -Wall -g -c kd_tree.cpp -o kd_tree.o
#g++ -Wall -g -c main.cpp -o main.o
#g++ -o aaa kd_tree.o main.o -LKD_TREE_H



